### ISSUE TITLE
Ruby Group Capstone - Set up the kanban board

### ISSUE THREAD

**Issue by adel-gu** [adel-gu/Catalog-of-my-things#19]
# For this Kanban board we accomplish the changes below:

- Linke for the `GitHub project`: https://github.com/adel-gu/Catalog-of-my-thingshttps://github.com/adel-gu/Catalog-of-my-things
- There are 04 members assigned to this project.
- **Team member 1**:  @Baayeh 
- **Team member 2**: @adel-gu 
- **Team member 3**  @RichardChileya 
- **Team member 4** @j-tee

**Comment by brytebee** [comment]
Hi, Team👋,

##

### Highlights💡
- Good commit message.✔️ 
- Good PR Summary.✔️
- Great UI design.✔️
- App functions as it should.✔️

##

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/3kuSo744UIPJjcJUEn/giphy.gif)

Good luck! 🎉 

##

###  **Optional Suggestions:**
- N/A

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
